name: utopic_tor_onion_proxy_example
description: Demonstrates how to use the utopic_tor_onion_proxy plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  utopic_tor_onion_proxy:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
