name: utopic_tor_onion_proxy
description: Flutter Plugin for Android, based on Android binary that start Tor Onion Proxy on random local socket.
version: 0.4.0
homepage: https://github.com/utopicnarwhal/utopic_tor_onion_proxy

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.utopicnarwhal.utopic_tor_onion_proxy
        pluginClass: UtopicTorOnionProxyPlugin
